apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: rabbitmq-operator
  template:
    metadata:
      labels:
        name: rabbitmq-operator
    spec:
      serviceAccountName: rabbitmq-operator
      containers:
        - name: rabbitmq-operator
          # Replace this with the built image name
          image: hub.xesv5.com/songdanyang/rabbitmq-operator:test
          command:
          - rabbitmq-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: rabbitmq
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "rabbitmq-operator"
